import type { Emitter } from './types.js';
import { familyToIdent, familyToKebab, groupByFamily, pickPrimaryFile } from './util.js';

/**
 * Emits a `next.fonts.ts` file using `next/font/local` — one `localFont` call
 * per family, with weights/styles bundled into the `src` array, plus a CSS
 * variable per family ready to spread into a root `<html>` element.
 */
export const nextEmitter: Emitter = (faces, ctx) => {
  const byFamily = groupByFamily(faces);
  if (byFamily.size === 0) return null;

  const lines: string[] = [
    '/* Auto-generated by fontfetch (`--emit next`). */',
    '/* Copy this folder into your Next.js project and import these exports. */',
    '/* Example: `<html className={`${interFont.variable} ${geistMono.variable}`}>` */',
    '',
    "import localFont from 'next/font/local';",
    '',
  ];

  for (const [family, list] of byFamily) {
    const ident = familyToIdent(family);
    const cssVar = `--font-${familyToKebab(family)}`;
    const sources = list
      .map((f) => pickPrimaryFile(f))
      .filter((s): s is { file: string; format: string | null } => s !== null);

    if (sources.length === 0) continue;

    lines.push(`export const ${ident} = localFont({`);
    lines.push('  src: [');
    list.forEach((f, i) => {
      const src = pickPrimaryFile(f);
      if (!src) return;
      const weight = f.weight || '400';
      const style = f.style || 'normal';
      lines.push(
        `    { path: './${ctx.filesDir}/${src.file}', weight: '${weight}', style: '${style}' },` +
          (i === list.length - 1 ? '' : ''),
      );
    });
    lines.push('  ],');
    lines.push(`  variable: '${cssVar}',`);
    lines.push("  display: 'swap',");
    lines.push('});');
    lines.push('');
  }

  return { filename: 'next.fonts.ts', content: lines.join('\n') };
};
