import type { Emitter } from './types.js';
import { familyToIdent, familyToKebab, groupByFamily, tailwindBucket } from './util.js';

/**
 * Emits a `tailwind.fonts.ts` snippet that maps each family into a bucket
 * (`sans` / `serif` / `mono`) using a heuristic, plus an explicit alias per
 * family for direct use (`font-<family-slug>`). Pairs with `--emit next`,
 * which provides the CSS variables this config references.
 */
export const tailwindEmitter: Emitter = (faces, ctx) => {
  void ctx;
  const byFamily = groupByFamily(faces);
  if (byFamily.size === 0) return null;

  const buckets: Record<'sans' | 'serif' | 'mono', string[]> = { sans: [], serif: [], mono: [] };
  const aliases: { alias: string; family: string; cssVar: string }[] = [];

  for (const family of byFamily.keys()) {
    const cssVar = `--font-${familyToKebab(family)}`;
    const bucket = tailwindBucket(family);
    buckets[bucket].push(`var(${cssVar})`);
    aliases.push({ alias: familyToIdent(family), family, cssVar });
  }

  const fallback: Record<'sans' | 'serif' | 'mono', string> = {
    sans: "'system-ui', 'sans-serif'",
    serif: "'Georgia', 'serif'",
    mono: "'ui-monospace', 'monospace'",
  };

  const lines: string[] = [
    '/* Auto-generated by fontfetch (`--emit tailwind`). */',
    '/* Merge `fonts` into your tailwind.config.ts -> theme.extend.fontFamily. */',
    '/* Pair with the Next.js setup from `--emit next` for CSS variables. */',
    '',
    "import type { Config } from 'tailwindcss';",
    '',
    "type FontFamilyConfig = NonNullable<NonNullable<Config['theme']>['extend']>['fontFamily'];",
    '',
    'export const fonts: FontFamilyConfig = {',
  ];

  for (const bucket of ['sans', 'serif', 'mono'] as const) {
    const vars = buckets[bucket];
    if (vars.length === 0) continue;
    const stack = [...vars.map((v) => `'${v}'`), fallback[bucket]].join(', ');
    lines.push(`  ${bucket}: [${stack}],`);
  }

  for (const { alias, family, cssVar } of aliases) {
    lines.push(`  '${alias}': ['var(${cssVar})', /* ${family} */],`);
  }

  lines.push('};');
  lines.push('');
  lines.push('export default fonts;');

  return { filename: 'tailwind.fonts.ts', content: lines.join('\n') };
};
