import type { Emitter } from './types.js';
import { familyToKebab, groupByFamily } from './util.js';

/**
 * Emits a W3C Design Tokens Community Group (DTCG) compatible JSON file.
 * Spec: https://tr.designtokens.org/format/
 *
 * Output shape:
 *
 * ```json
 * {
 *   "$schema": "https://design-tokens.github.io/community-group/format/tokens.schema.json",
 *   "font": {
 *     "family": {
 *       "inter": {
 *         "$type": "fontFamily",
 *         "$value": ["Inter", "Inter Fallback", "system-ui", "sans-serif"]
 *       }
 *     },
 *     "weight": {
 *       "regular": { "$type": "fontWeight", "$value": 400 },
 *       "bold":    { "$type": "fontWeight", "$value": 700 }
 *     },
 *     "size":   { "xs": { ... }, "sm": { ... }, ... },
 *     "lineHeight": { "tight": { ... }, "normal": { ... }, "loose": { ... } }
 *   }
 * }
 * ```
 *
 * Consumed by Style Dictionary, Tokens Studio for Figma, Specify, and any
 * tool that follows the DTCG draft. Sits alongside `next.fonts.ts` and
 * `tailwind.fonts.ts` in the per-site output dir.
 */
export const tokensEmitter: Emitter = (faces) => {
  const byFamily = groupByFamily(faces);
  if (byFamily.size === 0) return null;

  const familyTokens: Record<string, { $type: string; $value: string[]; $description?: string }> = {};
  const weightTokens: Record<string, { $type: string; $value: number }> = {};
  const seenWeights = new Set<number>();

  for (const [family, list] of byFamily) {
    const key = familyToKebab(family);
    familyTokens[key] = {
      $type: 'fontFamily',
      $value: [family, `${family} Fallback`, 'system-ui', 'sans-serif'],
    };

    for (const f of list) {
      const w = parseInt(f.weight, 10);
      if (Number.isFinite(w) && !seenWeights.has(w)) {
        seenWeights.add(w);
        weightTokens[weightLabel(w)] = { $type: 'fontWeight', $value: w };
      }
    }
  }

  // Default size + line-height ladders. Match Tailwind's defaults so a
  // designer + dev can hand off without a rosetta-stone discussion.
  const sizeTokens = {
    xs: { $type: 'dimension', $value: '0.75rem' },
    sm: { $type: 'dimension', $value: '0.875rem' },
    base: { $type: 'dimension', $value: '1rem' },
    lg: { $type: 'dimension', $value: '1.125rem' },
    xl: { $type: 'dimension', $value: '1.25rem' },
    '2xl': { $type: 'dimension', $value: '1.5rem' },
    '3xl': { $type: 'dimension', $value: '1.875rem' },
    '4xl': { $type: 'dimension', $value: '2.25rem' },
  };

  const lineHeightTokens = {
    tight: { $type: 'number', $value: 1.2 },
    snug: { $type: 'number', $value: 1.3 },
    normal: { $type: 'number', $value: 1.5 },
    relaxed: { $type: 'number', $value: 1.7 },
    loose: { $type: 'number', $value: 2 },
  };

  const out = {
    $schema: 'https://design-tokens.github.io/community-group/format/tokens.schema.json',
    $description: 'Generated by fontfetch — W3C DTCG-compatible design tokens.',
    font: {
      family: familyTokens,
      weight: weightTokens,
      size: sizeTokens,
      lineHeight: lineHeightTokens,
    },
  };

  return { filename: 'fonts.tokens.json', content: `${JSON.stringify(out, null, 2)}\n` };
};

/**
 * Map an OpenType weight value to a conventional design-token name.
 * Matches the labels Tailwind, Style Dictionary, and most design systems use.
 */
function weightLabel(weight: number): string {
  if (weight <= 100) return 'thin';
  if (weight <= 200) return 'extralight';
  if (weight <= 300) return 'light';
  if (weight <= 400) return 'regular';
  if (weight <= 500) return 'medium';
  if (weight <= 600) return 'semibold';
  if (weight <= 700) return 'bold';
  if (weight <= 800) return 'extrabold';
  return 'black';
}
