import type { FontFace, OrphanFile } from './types.js';
import type { ClassifiedFace, LicenseSummary } from './license.js';

export interface BuildFontsCssOptions {
  /** Extra blocks appended after the primary @font-face declarations. v1.2 uses this to splice CLS-killing fallback faces. */
  extraBlocks?: string[];
  /** Comment-block preamble of `<link rel=preload>` snippets — one line per family/file pair. */
  preloadHints?: string[];
}

export function buildFontsCss(faces: FontFace[], options: BuildFontsCssOptions = {}): string {
  const lines: string[] = [
    '/* Auto-generated by fontfetch */',
    '/* Drop this folder into your project and link this CSS file. */',
    '',
  ];

  if (options.preloadHints && options.preloadHints.length > 0) {
    lines.push(
      '/* Drop these preload links into your <head> for the fonts above the fold (one per primary cut): */',
    );
    for (const hint of options.preloadHints) lines.push(`/*  ${hint} */`);
    lines.push('');
  }

  for (const f of faces) {
    lines.push('@font-face {');
    lines.push(`  font-family: '${f.family}';`);
    lines.push(`  font-style: ${f.style};`);
    lines.push(`  font-weight: ${f.weight};`);
    // Default to `font-display: swap` when the source rule omits it. Eliminates
    // FOIT on the slow-4G case; matches what next/font and Fontsource ship.
    lines.push(`  font-display: ${f.display ?? 'swap'};`);
    const srcParts = f.sources.map((s) => {
      const local = `url('./files/${s.localFile}')`;
      return s.format ? `${local} format('${s.format}')` : local;
    });
    lines.push(`  src: ${srcParts.join(', ')};`);
    if (f.unicodeRange) lines.push(`  unicode-range: ${f.unicodeRange};`);
    lines.push('}');
    lines.push('');
  }

  if (options.extraBlocks && options.extraBlocks.length > 0) {
    for (const block of options.extraBlocks) {
      lines.push(block);
      lines.push('');
    }
  }

  return lines.join('\n');
}

/**
 * Build `<link rel="preload">` snippets that match the primary cuts in the
 * passed face list. Emitted as comments at the top of `fonts.css` for the
 * user to copy into their `<head>`. We dedupe by primary `url` and skip the
 * `crossorigin` foot-gun by including it always (matches what every browser
 * docs page recommends).
 */
export function buildPreloadHints(faces: FontFace[]): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const f of faces) {
    const primary = f.sources[0];
    if (!primary?.localFile) continue;
    if (seen.has(primary.localFile)) continue;
    seen.add(primary.localFile);
    const format = primary.format ?? 'woff2';
    out.push(
      `<link rel="preload" href="./files/${primary.localFile}" as="font" type="font/${format}" crossorigin>`,
    );
  }
  return out;
}

export function buildFontsJson(faces: FontFace[], orphans: OrphanFile[] = []): string {
  return JSON.stringify(
    {
      faces: faces.map((f) => ({
        family: f.family,
        weight: f.weight,
        style: f.style,
        display: f.display,
        unicodeRange: f.unicodeRange,
        files: f.sources.map((s) => ({ file: `files/${s.localFile}`, format: s.format })),
      })),
      orphan_files: orphans.map((o) => ({ file: `files/${o.file}`, url: o.url })),
    },
    null,
    2,
  );
}

export function buildReadme(
  host: string,
  faces: FontFace[],
  totalFiles: number,
  orphans: OrphanFile[] = [],
): string {
  const byFamily = new Map<string, FontFace[]>();
  for (const f of faces) {
    if (!byFamily.has(f.family)) byFamily.set(f.family, []);
    byFamily.get(f.family)!.push(f);
  }

  const lines: string[] = [
    `# Fonts from ${host}`,
    '',
    `Downloaded ${totalFiles} font file(s) across ${faces.length} @font-face declaration(s).`,
    '',
    '## Usage',
    '',
    '1. Copy this whole folder into your project (e.g. `public/fonts/` or `src/assets/fonts/`).',
    '2. Include `fonts.css` in your app (import it, or `<link rel="stylesheet" href="...">`).',
    '3. Reference the families below by `font-family` in your CSS.',
    '',
    '## Families',
    '',
  ];

  for (const [family, list] of byFamily) {
    lines.push(`### ${family}`);
    lines.push('');
    const variants = new Map<string, number>();
    for (const f of list) {
      const key = `${f.weight} / ${f.style}`;
      variants.set(key, (variants.get(key) || 0) + 1);
    }
    for (const [key, n] of variants) {
      lines.push(`- ${key}${n > 1 ? `  _(${n} subset files)_` : ''}`);
    }
    lines.push('');
  }

  if (orphans.length > 0) {
    lines.push('## Orphan files');
    lines.push('');
    lines.push(`These ${orphans.length} font file(s) were observed loading in the browser but came from a cross-origin stylesheet whose @font-face rules couldn't be read directly (common for Adobe Typekit and similar services). The files are downloaded into \`files/\` but **not referenced in \`fonts.css\`** — there's no family/weight/style metadata to construct a rule from.`);
    lines.push('');
    lines.push('To use them, inspect the live site\'s DevTools to find the matching @font-face declarations, then add them to your CSS pointing at the local files.');
    lines.push('');
    for (const o of orphans) {
      lines.push(`- \`files/${o.file}\` ← ${o.url}`);
    }
    lines.push('');
  }

  lines.push('## Notes');
  lines.push('');
  lines.push('- Multiple files per weight/style usually means the source split the font by `unicode-range` (Latin, Latin-Ext, Cyrillic, etc.). The browser only loads the subsets it needs — keep them all.');
  lines.push('- For local design exploration. Verify licensing before shipping to production.');
  lines.push('');
  return lines.join('\n');
}

/**
 * Emits LICENSE_REVIEW.md — a heuristic summary of which fonts on the site
 * are open/self-hostable, which are commercial (don't ship without a license),
 * and which couldn't be confidently classified.
 *
 * Not legal advice. The classifier is conservative on purpose; "unknown"
 * cases are the user's responsibility to verify.
 */
export function buildLicenseReview(
  host: string,
  classified: ClassifiedFace[],
  summary: LicenseSummary,
): string {
  const lines: string[] = [
    `# License review for ${host}`,
    '',
    '> Heuristic-only. Not legal advice. Verify before shipping.',
    '',
    '## Summary',
    '',
    `- ✅ **${summary.open} open** — safe to self-host`,
    `- ⚠️ **${summary.commercial} commercial** — do not ship without a license`,
    `- ❓ **${summary.unknown} unknown** — manual review needed`,
    '',
  ];

  const sections: Array<{ status: 'open' | 'commercial' | 'unknown'; title: string; note?: string }> = [
    { status: 'open', title: '## ✅ Open / self-hostable' },
    {
      status: 'commercial',
      title: '## ⚠️ Commercial — do not ship without a license',
      note: 'These came from a commercial foundry CDN. Bundling them into a production app without a paid license violates the foundry EULA.',
    },
    {
      status: 'unknown',
      title: '## ❓ Unknown — manual review',
      note: "Couldn't match against known CDN signatures or the known-open family list. Check the foundry, search Google Fonts for a free alternative, or inspect the site's CSS to confirm.",
    },
  ];

  for (const section of sections) {
    const items = classified.filter((c) => c.classification.status === section.status);
    if (items.length === 0) continue;
    lines.push(section.title);
    lines.push('');
    if (section.note) {
      lines.push(`_${section.note}_`);
      lines.push('');
    }
    const byFamily = new Map<string, typeof items>();
    for (const it of items) {
      const list = byFamily.get(it.face.family) ?? [];
      list.push(it);
      byFamily.set(it.face.family, list);
    }
    for (const [family, list] of byFamily) {
      lines.push(`### ${family}`);
      lines.push('');
      lines.push(`- ${list[0].classification.reason}`);
      const fileList = list.flatMap((it) =>
        it.face.sources
          .map((s) => s.localFile)
          .filter((f): f is string => Boolean(f))
          .map((f) => `files/${f} (${it.face.weight}/${it.face.style})`),
      );
      const unique = [...new Set(fileList)];
      if (unique.length > 0) {
        lines.push('- Files:');
        for (const f of unique) lines.push(`  - \`${f}\``);
      }
      lines.push('');
    }
  }

  return lines.join('\n');
}
