import type { FontFace } from './types.js';

export function buildFontsCss(faces: FontFace[]): string {
  const lines: string[] = [
    '/* Auto-generated by fontfetch */',
    '/* Drop this folder into your project and link this CSS file. */',
    '',
  ];
  for (const f of faces) {
    lines.push('@font-face {');
    lines.push(`  font-family: '${f.family}';`);
    lines.push(`  font-style: ${f.style};`);
    lines.push(`  font-weight: ${f.weight};`);
    if (f.display) lines.push(`  font-display: ${f.display};`);
    const srcParts = f.sources.map((s) => {
      const local = `url('./files/${s.localFile}')`;
      return s.format ? `${local} format('${s.format}')` : local;
    });
    lines.push(`  src: ${srcParts.join(', ')};`);
    if (f.unicodeRange) lines.push(`  unicode-range: ${f.unicodeRange};`);
    lines.push('}');
    lines.push('');
  }
  return lines.join('\n');
}

export function buildFontsJson(faces: FontFace[]): string {
  return JSON.stringify(
    faces.map((f) => ({
      family: f.family,
      weight: f.weight,
      style: f.style,
      display: f.display,
      unicodeRange: f.unicodeRange,
      files: f.sources.map((s) => ({ file: `files/${s.localFile}`, format: s.format })),
    })),
    null,
    2,
  );
}

export function buildReadme(host: string, faces: FontFace[], totalFiles: number): string {
  const byFamily = new Map<string, FontFace[]>();
  for (const f of faces) {
    if (!byFamily.has(f.family)) byFamily.set(f.family, []);
    byFamily.get(f.family)!.push(f);
  }

  const lines: string[] = [
    `# Fonts from ${host}`,
    '',
    `Downloaded ${totalFiles} font file(s) across ${faces.length} @font-face declaration(s).`,
    '',
    '## Usage',
    '',
    '1. Copy this whole folder into your project (e.g. `public/fonts/` or `src/assets/fonts/`).',
    '2. Include `fonts.css` in your app (import it, or `<link rel="stylesheet" href="...">`).',
    '3. Reference the families below by `font-family` in your CSS.',
    '',
    '## Families',
    '',
  ];

  for (const [family, list] of byFamily) {
    lines.push(`### ${family}`);
    lines.push('');
    const variants = new Map<string, number>();
    for (const f of list) {
      const key = `${f.weight} / ${f.style}`;
      variants.set(key, (variants.get(key) || 0) + 1);
    }
    for (const [key, n] of variants) {
      lines.push(`- ${key}${n > 1 ? `  _(${n} subset files)_` : ''}`);
    }
    lines.push('');
  }

  lines.push('## Notes');
  lines.push('');
  lines.push('- Multiple files per weight/style usually means the source split the font by `unicode-range` (Latin, Latin-Ext, Cyrillic, etc.). The browser only loads the subsets it needs — keep them all.');
  lines.push('- For local design exploration. Verify licensing before shipping to production.');
  lines.push('');
  return lines.join('\n');
}
